#cloud-config
version: v1

hostname: ${hostname}
fqdn: ${domain}
packages_update: true
packages_upgrade: true

users:
  - name: sysadmin
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD13ASx5XXMHPDNJUyBi/cYhJm3Un75LdqgxcBN2CiKbLlMLtQit0PUvAS9WLsqhXkaAa4gzw4Wkl2LgrNxohclIy2MKr36GqZ25NBm/pg2a+YLzWfKZZAeJrLbT2CtE6VeV9h1hQD5rw1V9+fdaGL+pOYgSsACjVl2FCUI58lq82036jbj1W+2JreYNpwhMkCBjsyvNDCCmGcMoNbNID4QbC3DNM7TQlxXvXXe0xmmmaF0dsNipezdS8Xf2Jjhu/Ce3G9gfPnxAopP6SPM02mQUJjoo4zdFk7S8jdEcdR6NUqvlReriXX7PlKVnGokKGkpKQjFiRmGRVOuXFKDDNhR8IZHRjmXTE/kwamzlS97Q/3r3cAxPAs+KAQp6DwO7RlFT1kr8Xuwklvr+OkpNzbZPWci4F4+XxkThRbGCGvUKJC4WfUgrjTDNOW1eXCUaPNq6FAlDGhjGqslFwCz3YFdrqQFQQhuxQf3hELBF/yUG86E2RKiZv6rHHNJaLN4asE= symmetry
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyVl8oR7SP1i1UCa/3Imve9kEVqitST3/KeKcvbuwSxSSfDMy50r9i/OG9hN0gi6mKVMBGr51jOax0hu42mU3n2uno5Qr+NacoFzB6v2Er1rXXx9k89ca2rOOb4ltu4cLryiTbPgyENj2+Zdw5J/sNyIr9z9wRgIqWpbYQyKn93qWmt/23hJcYsStxwNf8cXKXt9TjIuWH1G6W4DOUC0IM1bFInsBVrK6lJunA/3EaVpmWI/FmcKC16Tnek9MPOnvOMhDSjkdFKd/b/6TK2C702A9DOADEAOaSFpXupPDys9uLZHsfJB2PfvcoZ6C/HW78mzsZcrUh2oni+nFAyiEAtyaZzGyXp4QZ3pcduowKj617gRUsRI2PR8LGtYqOey/l0Ln/Az0V/M9QP+ASf2Zkfcpqmpip9iUv3Ja7RLmuzWjEeaeFkKg+54TildB/SHCkvW03afD/d92Ez2ao0G27R2B2BNresxyC3n3pJnSEJkGZQXVg6HfKICb07bkOwtM= fgl-kvm
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

# Qemu-guest-agent configuration
write_files:
  - path: /etc/apparmor.d/abstractions/libvirt-qemu
    content: /var/lib/libvirt/qemu/channel/target/* rw
  
  - path: /etc/cloud/cloud-init.disabled

# Install qemu-guest-agent to retireve information about our servers
packages:
  - qemu-guest-agent

# Restart the qemu-agent process
runcmd: 
  - kill $(pidof qemu-ga)
  - /usr/sbin/qemu-ga -d
