packages:
  - mariadb-server
  - nginx

php_packages:
  - php-cgi 
  - php-common 
  - php-fpm 
  - php-pear 
  - php-mbstring 
  - php-zip 
  - php-net-socket 
  - php-gd 
  - php-xml-util 
  - php-gettext 
  - php-mysql 
  - php-bcmath
