---
- name: Updating & Upgrading system packages
  become: True
  become_method: sudo
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400
    upgrade: yes

- name: Installing Docker Prerequisites packages
  become: True
  become_method: sudo
  ansible.builtin.apt:
    pkg: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: true

- name: Creating Docker GPG Keyring directory
  become: True
  become_method: sudo
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Adding Docker GPG Keys
  become: True
  become_method: sudo
  ansible.builtin.shell: | 
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Adding the Docker repository 
  become: True
  become_method: sudo
  ansible.builtin.shell: |
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Installing Docker Engine and dependencies
  become: True
  become_method: sudo
  ansible.builtin.apt:
    pkg: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Adding Admin user to the Docker group
  become: True
  become_method: sudo
  ansible.builtin.user:
    name: sysadmin
    groups: docker
    append: yes

- name: Adding Docker-Compose configurations files to the server
  become: True
  become_method: sudo
  ansible.builtin.copy:
    src: docker
    dest: /home/sysadmin
