---
version: "2.1"
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Toronto
    volumes:
      - ${HOME}/.config/dokuwiki:/config
    ports:
      - 0.0.0.0:82:80
      - 0.0.0.0:1443:443
    restart: unless-stopped
