#!/usr/bin/env bash

# This script is meant to be sourced to get access to our system variables used
# in other various scripts & tools

# Specify where we store our different Cloud Images
FGL_TEMPLATE_PATH="/data/isos"

# Specify where the VMs are to be stored
FGL_DISK_PATH="/data/images"

# Location of cloud-init scripts to be used
FGL_CLOUD_INIT_PATH="/data/cloud-init"

